const config=window.GUILD_CONFIG||{},data=window.GUILD_DATA||{};
const $=id=>document.getElementById(id);
const safeText=(tag,text,cls)=>{const e=document.createElement(tag);e.textContent=text||'';if(cls)e.className=cls;return e};
const roster=$('rosterCards');(data.roster||[]).forEach(m=>{const card=safeText('article','','member');card.append(safeText('div',m.initial,'avatar'),safeText('span',m.role,'role'),safeText('h3',m.name),safeText('p',m.className));roster.append(card)});
const news=$('newsCards');(data.news||[]).forEach(n=>{const card=safeText('article','','news-card');card.append(safeText('span',n.date,'date'),safeText('h3',n.title),safeText('p',n.body));news.append(card)});
const gallery=$('galleryCards');(data.gallery||[]).forEach(g=>{const card=safeText('article','','gallery-card'),visual=safeText('div','','gallery-image'),copy=safeText('div','','copy');if(g.image){const img=document.createElement('img');img.src=g.image;img.alt=g.title;img.loading='lazy';visual.append(img)}else visual.textContent='⚔';copy.append(safeText('h3',g.title),safeText('p',g.caption));card.append(visual,copy);gallery.append(card)});
$('menu').addEventListener('click',()=>{const open=$('nav').classList.toggle('open');$('menu').setAttribute('aria-expanded',String(open))});document.querySelectorAll('#nav a').forEach(a=>a.addEventListener('click',()=>{$('nav').classList.remove('open');$('menu').setAttribute('aria-expanded','false')}));
$('applyForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),email=config.recruitmentEmail;if(!email||!/^\S+@\S+\.\S+$/.test(email)){$('applyStatus').textContent='Applications are not configured yet. Please join our Discord to apply.';window.open(config.discordInvite||'https://discord.gg/cuGad4an','_blank','noopener,noreferrer');return}const subject=`Guild application: ${f.get('character')}`;const body=`Character: ${f.get('character')}\nClass / Spec: ${f.get('classSpec')}\nExperience: ${f.get('experience')}\n\nMessage:\n${f.get('message')||'(none)'}`;location.href=`mailto:${encodeURIComponent(email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;$('applyStatus').textContent='Your email app should open with your application. Send the email to finish applying.'});
const dialog=$('loginDialog');$('loginBtn').addEventListener('click',()=>dialog.showModal());
let auth=null;const authStatus=$('authStatus');const firebase=config.firebaseConfig;
if(firebase&&firebase.apiKey&&firebase.projectId&&firebase.appId){try{const [{initializeApp},{getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,signOut}]=await Promise.all([import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js')]);auth=getAuth(initializeApp(firebase));onAuthStateChanged(auth,user=>{if(user){$('authArea').replaceChildren(safeText('p',`Signed in as ${user.email}. Guild-only content can be added here.`));const out=safeText('button','SIGN OUT','btn secondary');out.type='button';out.addEventListener('click',()=>signOut(auth).then(()=>location.reload()));$('authArea').append(out);$('loginBtn').textContent='MEMBER PORTAL'}else $('loginBtn').textContent='MEMBER LOGIN'});const credentials=()=>[$('email').value.trim(),$('password').value];$('signIn').addEventListener('click',async()=>{try{const [email,password]=credentials();await signInWithEmailAndPassword(auth,email,password);authStatus.textContent='Signed in.'}catch(err){authStatus.textContent='Sign-in failed. Check your details or account setup.'}});$('signUp').addEventListener('click',async()=>{try{const [email,password]=credentials();await createUserWithEmailAndPassword(auth,email,password);authStatus.textContent='Account created.'}catch(err){authStatus.textContent='Could not create account. Check your details and Firebase settings.'}})}catch(err){authStatus.textContent='Member login could not load. Please try again later.'}}else{authStatus.textContent='Member accounts are not enabled yet. Join our Discord in the meantime.';$('authArea').hidden=true}
